name: Create Enviroment
on: [workflow_dispatch]

jobs:
  Create-iis-site:
   runs-on: self-hosted
   env:
      website-name: trinkshmg
      app-pool-name: trinks-app
      website-host-header: trinks-app
      website-path: C:\inetpub\wwwroot\Trinks-H01
      port: 80

   steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Create Web Site
      working-directory: c:\Windows\System32\inetsrv
      shell: cmd
      run: |
        appcmd add site /name:${{ env.website-name }} /bindings:http/*:${{ env.port }}:${{ env.website-host-header}}  /physicalpath:"${{ env.website-path }}"
        appcmd set site /site.name: ${{ env.website-name }} /[path='/'].applicationPool: ${{ env.app-pool-name }}