name: Create Enviroment


on: 
  workflow_dispatch:
    inputs:
      website-name:
        description: 'The name of the website.'
        required: true
      website-path:
        description: 'The local directory location of the web site.'
        required: true
      port:
        description: 'The port you will use.'
        required: true
env:
      app-pool-name: trinks-app
      website-host-header: trinkshmg
      directory: C:\Sites\Branches\${{ github.ref_name }}

jobs:

  test-path:
    runs-on: self-hosted

    steps:
    - name: Check if directory exists
      run: |
        $folder = "${{ env.directory }}"
        $dir = "${{ env.directory }}"
        if (Test-Path $dir) {
        Write-Host "Directory exists."
        echo ::set-env name=FOLDER_EXISTS::true
        exit 0
        } else {
        Write-Host "Directory does not exist. Creating..."
        mkdir $folder
        mkdir $folder\Api
        mkdir $folder\ProApi
        mkdir $folder\Services
        mkdir $folder\WindowsService
        mkdir $folder\LinkDePagamento
        echo ::set-env name=FOLDER_EXISTS::false
        exit 0
        }

  Create-iis-site:
   if: outputs.FOLDER_EXISTS == 'false'
   runs-on: self-hosted
   needs: test-path
   
   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
    
    - name: Create Web Site
      working-directory: c:\Windows\System32\inetsrv
      shell: cmd
      run: |
        appcmd add site /name:${{ inputs.website-name }} /bindings:http/*:${{ inputs.port }}:${{ env.website-host-header}}  /physicalpath:"${{ inputs.website-path }}"
        appcmd set site /site.name:${{ inputs.website-name }} /[path='/'].applicationPool:${{ env.app-pool-name }}
        appcmd list site ${{ inputs.website-name }}