name: Create Enviroment


on: 
  workflow_dispatch:
    inputs:
      website-name:
        description: 'The name of the website.'
        required: true
      website-path:
        description: 'The local directory location of the web site.'
        required: true
      port:
        description: 'The port you will use.'
        required: true
env:
      app-pool-name: trinks-app
      website-host-header: trinkshmg
      directory: C:\Sites\Branches\${{ github.ref_name }}

jobs:

  test-path:
    runs-on: self-hosted

    steps:
    - name: Check if directory exists
      run: |
        $dir = "${{ env.directory }}"
        if (Test-Path $dir) {
        Write-Host "Directory exists"
        exit 1
        } else {
        Write-Host "Directory does not exist"
        exit 0
        }

  creat-folder:
    needs: test-path
    runs-on: self-hosted
    if: needs.test-path.outputs.exit-code == '0'
    steps:
      - name: Create Folder
        run: |
          echo Creating Folders...
          mkdir C:\Sites\Branches\${{ github.ref_name }}
          mkdir C:\Sites\Branches\${{ github.ref_name }}\Api
          mkdir C:\Sites\Branches\${{ github.ref_name }}\ProApi
          mkdir C:\Sites\Branches\${{ github.ref_name }}\Services
          mkdir C:\Sites\Branches\${{ github.ref_name }}\WindowsService
          mkdir C:\Sites\Branches\${{ github.ref_name }}\LinkDePagamento

  Create-iis-site:
   runs-on: self-hosted
   needs: [test-path,creat-folder]

   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
    
    - name: Create Web Site
      if: needs.test-path.outputs.exit-code == '0'
      working-directory: c:\Windows\System32\inetsrv
      shell: cmd
      run: |
        appcmd add site /name:${{ inputs.website-name }} /bindings:http/*:${{ inputs.port }}:${{ env.website-host-header}}  /physicalpath:"${{ inputs.website-path }}"
        appcmd set site /site.name:${{ inputs.website-name }} /[path='/'].applicationPool:${{ env.app-pool-name }}
        appcmd list site ${{ inputs.website-name }}