name: Create Enviroment


on: 
  workflow_dispatch:
    inputs:
      website-name:
        description: 'The name of the website.'
        required: true
      website-path:
        description: 'The local directory location of the web site.'
        required: true
      port:
        description: 'The port you will use.'
        required: true
env:
      app-pool-name: trinks-app
      website-host-header: trinkshmg
      exit: teste

jobs:

  test-path:
    runs-on: self-hosted
    outputs:
      path: ${{steps.test_path.outputs.path}}
    steps:
      - name: Test path
        id: test_path
        run: |
          $path= Test-Path "C:\Sites\Branches\${{ github.ref_name }}"
          echo $path
          echo $path=path >> $GITHUB_OUTPUT

  create-folder:
    needs: test-path
    if: ${{needs.test_path.outputs.path}} == 'False'
    runs-on: self-hosted
    steps:
      - name: Create Folder
        run: |
          mkdir C:\Sites\Branches\${{ github.ref_name }}
          mkdir C:\Sites\Branches\${{ github.ref_name }}\Api
          mkdir C:\Sites\Branches\${{ github.ref_name }}\ProApi
          mkdir C:\Sites\Branches\${{ github.ref_name }}\Services
          mkdir C:\Sites\Branches\${{ github.ref_name }}\WindowsService
          mkdir C:\Sites\Branches\${{ github.ref_name }}\LinkDePagamento
  Create-iis-site:
   runs-on: self-hosted
   needs: create-folder

   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
        run: echo "${{ toJson(github) }}"
    
    - name: Create Web Site
      working-directory: c:\Windows\System32\inetsrv
      shell: cmd
      run: |
        appcmd add site /name:${{ inputs.website-name }} /bindings:http/*:${{ inputs.port }}:${{ env.website-host-header}}  /physicalpath:"${{ inputs.website-path }}"
        appcmd set site /site.name:${{ inputs.website-name }} /[path='/'].applicationPool:${{ env.app-pool-name }}
        appcmd list site ${{ inputs.website-name }}