name: Delete Enviroment

on: 
  workflow_dispatch:
    inputs:
      website-name:
        description: 'The name of the website.'
        required: true

jobs:
  Delete-iis-site:
   runs-on: self-hosted

   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
    
    - name: Create Web Site
      working-directory: c:\Windows\System32\inetsrv
      shell: cmd
      run: |
        appcmd delete site ${{ inputs.website-name }}