name: Delete Enviroment

on: 
  delete:
    branches: 
      - **-**

jobs:
  Delete-iis-site:
   runs-on: self-hosted

   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
    
    - name: Create Web Site
      working-directory: c:\Windows\System32\inetsrv
      shell: cmd
      run: |
        appcmd delete site ${{ inputs.website-name }}