name: Delete Enviroment

on: 
  delete:
    branches: 
      - '**'

jobs:
  Delete-iis-site:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
    
    - name: Git Json 
      run: echo "${{ toJson(github) }}"
    
    - name: Set Branch name
      run: |
          BRANCH=$(cat ${{ github.event_path }} | jq --raw-output '.ref')
          echo "${{ github.repository }} has ${BRANCH} branch"
          echo ":: name=STAGE::$(echo ${BRANCH})"
    - name: Echo Branch name
      run: echo Deleting from STAGE:$STAGE