name: Delete Enviroment

on: 
  delete:
    branches: 
      - '**'

jobs:
  Delete-iis:
   runs-on: ubuntu-latest
   outputs:
     test: ${{ steps.branch.outputs.test }}

   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
    
    - name: Git Json 
      run: echo "${{ toJson(github) }}"
    
    - name: Set Branch name
      id: branch
      run: |
          echo test=$(cat ${{ github.event_path }} | jq --raw-output '.ref') >> $GITHUB_OUTPUT
          
  Delete-iis-site:
    needs: Delete-iis
    runs-on: self-hosted
    steps:
    - name: Delete Web Site
      working-directory: c:\Windows\System32\inetsrv
      shell: cmd
      run: |
        appcmd delete site ${{needs.Delete-iis.outputs.test}}