name: Teste de Fila

on:
  workflow_dispatch: {}

jobs:
  aguardar_na_fila:
    runs-on: windows-latest
    steps:
      - name: Aguardar na fila
        shell: powershell
        run: |
          $jobId = $env:GITHUB_RUN_ID
          $body = @{ job_id = $jobId } | ConvertTo-Json -Compress
          Write-Host "Aguardando na fila com Job ID: $jobId"
          $response = Invoke-WebRequest -Uri "http://3.235.45.10:5000/enqueue" -Method Post -Body $body -ContentType "application/json"
          Write-Host "Resposta da fila: $($response.Content)"

  executar_tarefa:
    runs-on: [self-hosted, casa]
    needs: aguardar_na_fila
    steps:
      - name: Executar tarefa principal
        shell: powershell
        run: |
          Write-Host "Iniciando o job de teste, rodando por 1 minuto."
          for ($i = 1; $i -le 60; $i++) {
            Write-Host "Executando passo $i/60"
            Start-Sleep -Seconds 1
          }
          Write-Host "Job de teste concluído."

  liberar_fila:
    runs-on: [self-hosted, casa]
    needs: executar_tarefa
    if: always()
    steps:
      - name: Liberar fila
        shell: powershell
        run: |
          $jobId = $env:GITHUB_RUN_ID
          $body = @{ job_id = $jobId } | ConvertTo-Json -Compress
          Write-Host "Liberando a fila com Job ID: $jobId"
          $response = Invoke-WebRequest -Uri "http://3.235.45.10:5000/release" -Method Post -Body $body -ContentType "application/json"
          Write-Host "Resposta da liberação: $($response.Content)"
