name: Jira Card Creator

on:
  pull_request:
    types: [opened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Check pull request status
      run: |
        if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
          echo "Pull request not merged, skipping...";
          exit 0;
        fi
    
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  
    - name: Create
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: EX
        issuetype: Solicitação de Extração
        summary: ${{ github.event.pull_request.title }}

    - name: Log created issue
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
      run: echo "Issue ${{ steps.create.data.key }} was created"
    
    - name: Transition to "MERGEADO"
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged }}
      uses: atlassian/gajira-transition@v3
      with:
        issueKey: ${{ steps.create.data.key }}
        transitionName: MERGEADO
