name: Jira Card Creator

on:
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: https://perlink.atlassian.net/
        JIRA_USER_EMAIL: matheus.lima@trinks.com
        JIRA_API_TOKEN: ATATT3xFfGF01-M0ryPGwI-nIWH6jKaklcXGtXDPRjwi8X2o9Cc3pMZCGismg8wbyTPH74xyQX7LIwcV9wZBLmJYBJM464YSaEd8LMg-S3sJWnIumOlHjLPGZN3vW3BYPFPfB4bgG20xhyUBfwAULcH8cJGNCDQguEMETX50-C_r1t1QMa8LhH4=0899A6CF

  
    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: EX
        issuetype: Build
        summary: ${{ github.event.pull_request.title }}

    - name: Log created issue
      run: echo "Issue ${{ github.event.pull_request.title }} was created"
