name: Update App
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: [self-hosted,linux]
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false
    
    - name: Build App
      run: sudo docker build -t calcflask:$GITHUB_SHA /home/ubuntu/actions-runner/_work/Calculator-Flask/Calculator-Flask/Web/calc-docker
    
    - name: Run App
      run: sudo docker run -d -p 80:80 calcflask:$GITHUB_SHA